# Operators

In [1]:
import pandas as pd

table = pd.read_html('https://www.w3schools.com/python/python_operators.asp')
table[0]

  Operator            Name Example    Try it
0        +        Addition   x + y  Try it »
1        -     Subtraction   x - y  Try it »
2        *  Multiplication   x * y  Try it »
3        /        Division   x / y  Try it »
4        %         Modulus   x % y  Try it »
5       **  Exponentiation  x ** y  Try it »
6       //  Floor division  x // y  Try it »

In [2]:
table[1]

   Operator  Example     Same As    Try it
0         =    x = 5       x = 5  Try it »
1        +=   x += 3   x = x + 3  Try it »
2        -=   x -= 3   x = x - 3  Try it »
3        *=   x *= 3   x = x * 3  Try it »
4        /=   x /= 3   x = x / 3  Try it »
5        %=   x %= 3   x = x % 3  Try it »
6       //=  x //= 3  x = x // 3  Try it »
7       **=  x **= 3  x = x ** 3  Try it »
8        &=   x &= 3   x = x & 3  Try it »
9        |=   x |= 3   x = x | 3  Try it »
10       ^=   x ^= 3   x = x ^ 3  Try it »
11      >>=  x >>= 3  x = x >> 3  Try it »
12      <<=  x <<= 3  x = x << 3  Try it »

In [3]:
table[2]

  Operator                      Name Example    Try it
0       ==                     Equal  x == y  Try it »
1       !=                 Not equal  x != y  Try it »
2        >              Greater than   x > y  Try it »
3        <                 Less than   x < y  Try it »
4       >=  Greater than or equal to  x >= y  Try it »
5       <=     Less than or equal to  x <= y  Try it »

# Walrus operator (:=) start 3.8 python

In [1]:
n = 15
if (m := n) > 10:
    print(f"{m} is greater than 10")
else:
    print(f"{m} is not greater than 10")
print("-----------")    
    
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = []

for item in data:
    if item > 5:
        result.append(item)
print(f"Data List: {data}")
print(f"Greater than 5: {result}")

    
print("-----------")

numbers = [1, 4, 7, 2, 8, 5]
threshold = 5
index = 0

while (current := numbers[index]) < threshold:
    print(f"Processing {current} (index {index})")
    index += 1

print(f"Stopped at {current} (index {index}), as it is greater than or equal to {threshold}")

15 is greater than 10
-----------
Data List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Greater than 5: [6, 7, 8, 9, 10]
-----------
Processing 1 (index 0)
Processing 4 (index 1)
Stopped at 7 (index 2), as it is greater than or equal to 5